services:
  - type: web
    name: yildiz-deva
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        value: devadmin123
        scope: run
    # Render'da SQL için kullanıcı oluştur
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
